# Generated by Django 5.1.3 on 2024-11-23 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notaventa',
            name='user_id',
            field=models.IntegerField(default=0),
        ),
    ]
