# Generated by Django 5.1.3 on 2024-11-23 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_parabrisas_categoria_remove_notaventa_factura_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='almacenparabrisa',
            old_name='almacen_id',
            new_name='almacen',
        ),
        migrations.RenameField(
            model_name='almacenparabrisa',
            old_name='parabrisa_id',
            new_name='parabrisa',
        ),
        migrations.RenameField(
            model_name='notacompra',
            old_name='almacen_id',
            new_name='almacen',
        ),
        migrations.RenameField(
            model_name='notacompra',
            old_name='parabrisa_id',
            new_name='parabrisa',
        ),
        migrations.RenameField(
            model_name='notacompra',
            old_name='proveedor_id',
            new_name='proveedor',
        ),
        migrations.RenameField(
            model_name='notaventa',
            old_name='almacen_id',
            new_name='almacen',
        ),
        migrations.RenameField(
            model_name='notaventa',
            old_name='cliente_id',
            new_name='cliente',
        ),
    ]
