# Generated by Django 5.1.3 on 2024-11-23 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_rename_almacen_id_almacenparabrisa_almacen_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacenparabrisa',
            name='almacen',
            field=models.ForeignKey(db_column='almacen_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.almacen'),
        ),
        migrations.RenameField(
            model_name='almacenparabrisa',
            old_name='almacen',
            new_name='almacen_id',
        ),
        migrations.AlterField(
            model_name='almacenparabrisa',
            name='parabrisa',
            field=models.ForeignKey(db_column='parabrisa_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.parabrisas'),
        ),
        migrations.RenameField(
            model_name='almacenparabrisa',
            old_name='parabrisa',
            new_name='parabrisa_id',
        ),
        migrations.AlterField(
            model_name='notacompra',
            name='almacen',
            field=models.ForeignKey(db_column='almacen_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.almacen'),
        ),
        migrations.RenameField(
            model_name='notacompra',
            old_name='almacen',
            new_name='almacen_id',
        ),
        migrations.AlterField(
            model_name='notacompra',
            name='parabrisa',
            field=models.ForeignKey(db_column='parabrisa_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.parabrisas'),
        ),
        migrations.RenameField(
            model_name='notacompra',
            old_name='parabrisa',
            new_name='parabrisa_id',
        ),
        migrations.AlterField(
            model_name='notacompra',
            name='proveedor',
            field=models.ForeignKey(db_column='proveedor_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.proveedor'),
        ),
        migrations.RenameField(
            model_name='notacompra',
            old_name='proveedor',
            new_name='proveedor_id',
        ),
        migrations.AlterField(
            model_name='notaventa',
            name='almacen',
            field=models.ForeignKey(db_column='almacen_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.almacen'),
        ),
        migrations.RenameField(
            model_name='notaventa',
            old_name='almacen',
            new_name='almacen_id',
        ),
        migrations.AlterField(
            model_name='notaventa',
            name='cliente',
            field=models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.cliente'),
        ),
        migrations.RenameField(
            model_name='notaventa',
            old_name='cliente',
            new_name='cliente_id',
        ),
        migrations.AlterField(
            model_name='notaventa',
            name='factura_id',
            field=models.IntegerField(db_column='factura_id', default=0),
        ),
    ]
