# Generated by Django 5.1.3 on 2024-11-23 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_almacenparabrisa_almacen_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='parabrisas',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='parabrisas',
            old_name='posicion',
            new_name='posicion_id',
        ),
        migrations.RenameField(
            model_name='parabrisas',
            old_name='vehiculo',
            new_name='vehiculo_id',
        ),
        migrations.RemoveField(
            model_name='parabrisas',
            name='total',
        ),
        migrations.AddField(
            model_name='parabrisas',
            name='observacion',
            field=models.CharField(default='sirve', max_length=255),
        ),
    ]
