# Generated by Django 5.1.3 on 2024-11-24 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_almacen_id_alter_almacenparabrisa_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notaventa',
            name='factura_id',
        ),
        migrations.CreateModel(
            name='NotaVentaParabrisa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField()),
                ('nota_venta_id', models.ForeignKey(db_column='nota_venta_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.notaventa')),
                ('parabrisa_id', models.ForeignKey(db_column='parabrisa_id', on_delete=django.db.models.deletion.CASCADE, to='myapp.parabrisas')),
            ],
        ),
    ]
